const mongoose=require('mongoose');
const user_schema=new mongoose.Schema({
    name:{
        required:true,
        type:String
    },
    email:{
    required:true,
    type:String
    },
    password:{
     required:true,
     type:String
    },
    ExamDate:{
        required:true,
        type:Date,
    },
      ExamCenter:{
        required:true,
        type:String,
    },
      State:{
        required:true,
        type:String,
    },
     City:{
        required:true,
        type:String,
    },
      Number:{
        required:true,
        type:String,
    },
    Auditor_Reporting_Time:{
       type:String,
    },
     Student_Entry_Time:{
       type:String,
    },
    Exam_Starting_Time:{
        type:String,
    }
})
const user=mongoose.model('user',user_schema);
module.exports=user;